DEBUG = True
SQLALCHEMY_DATABASE_URI = "sqlite:///storage.db"
SECRET_KEY = 'codigo_expresso'
RECAPTCHA_PUBLIC_KEY = "6LeYIbsSAAAAACRPIllxA7wvXjIE411PfdB2gt2J"
RECAPTCHA_PRIVATE_KEY = "6LeYIbsSAAAAAJezaIq3Ft_hSTo0YtyeFG-JgRtu"